ECL now builds against third-party versions of the Boehm-Weiser garbage collector

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -9814,27 +9814,322 @@ LSP_FEATURES="(cons :wants-rt ${LSP_FEATURES})"
 fi
 
 
-if test ${enable_boehm} = "included"; then
-  { echo "$as_me:$LINENO: Configuring included Boehm GC library:" >&5
+case "${enable_boehm}" in
+  included)
+    { echo "$as_me:$LINENO: Configuring included Boehm GC library:" >&5
 echo "$as_me: Configuring included Boehm GC library:" >&6;}
-  test -d gc && rm -rf gc
-  if mkdir gc; then
+    test -d gc && rm -rf gc
+    if mkdir gc; then
      (destdir=`${PWDCMD}`; cd gc; \
       CC="${CC} ${PICFLAG}" CFLAGS="${CFLAGS}" LDFLAGS="${LDFLAGS}" \
         $srcdir/gc/configure --disable-shared --prefix=${destdir} \
 	--includedir=${destdir}/ecl/gc/ --libdir=${destdir} --build=${build_alias} \
 	--host=${host_alias} ${boehm_configure_flags})
-     ECL_BOEHM_GC_HEADER='ecl/gc/gc.h'
+      ECL_BOEHM_GC_HEADER='ecl/gc/gc.h'
+    else
+      { { echo "$as_me:$LINENO: error: Unable to create 'gc' directory" >&5
+echo "$as_me: error: Unable to create 'gc' directory" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    ;;
+  system)
+    if test "${ac_cv_header_gc_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for gc.h" >&5
+echo $ECHO_N "checking for gc.h... $ECHO_C" >&6
+if test "${ac_cv_header_gc_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_gc_h" >&5
+echo "${ECHO_T}$ac_cv_header_gc_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking gc.h usability" >&5
+echo $ECHO_N "checking gc.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <gc.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking gc.h presence" >&5
+echo $ECHO_N "checking gc.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <gc.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
   else
-     if test -f /usr/include/gc/gc.h -o test -f /usr/local/include/gc/gc.h; then
-        ECL_BOEHM_GC_HEADER='gc/gc.h'
-     else
-        ECL_BOEHM_GC_HEADER='gc.h'
-     fi
+    ac_cpp_err=
   fi
 else
-  ECL_BOEHM_GC_HEADER='none'
+  ac_cpp_err=yes
 fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: gc.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: gc.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gc.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: gc.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: gc.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: gc.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gc.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: gc.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gc.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: gc.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gc.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: gc.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gc.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: gc.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gc.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: gc.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------ ##
+## Report this to the ecl lists.  ##
+## ------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for gc.h" >&5
+echo $ECHO_N "checking for gc.h... $ECHO_C" >&6
+if test "${ac_cv_header_gc_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_gc_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_gc_h" >&5
+echo "${ECHO_T}$ac_cv_header_gc_h" >&6
+
+fi
+if test $ac_cv_header_gc_h = yes; then
+  ECL_BOEHM_GC_HEADER='gc.h'
+fi
+
+
+    if test -z "$ECL_BOEHM_GC_HEADER"; then
+       if test "${ac_cv_header_gc_gc_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for gc/gc.h" >&5
+echo $ECHO_N "checking for gc/gc.h... $ECHO_C" >&6
+if test "${ac_cv_header_gc_gc_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_gc_gc_h" >&5
+echo "${ECHO_T}$ac_cv_header_gc_gc_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking gc/gc.h usability" >&5
+echo $ECHO_N "checking gc/gc.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <gc/gc.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking gc/gc.h presence" >&5
+echo $ECHO_N "checking gc/gc.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <gc/gc.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: gc/gc.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: gc/gc.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gc/gc.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: gc/gc.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: gc/gc.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: gc/gc.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gc/gc.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: gc/gc.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gc/gc.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: gc/gc.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gc/gc.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: gc/gc.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gc/gc.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: gc/gc.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gc/gc.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: gc/gc.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------ ##
+## Report this to the ecl lists.  ##
+## ------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for gc/gc.h" >&5
+echo $ECHO_N "checking for gc/gc.h... $ECHO_C" >&6
+if test "${ac_cv_header_gc_gc_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_gc_gc_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_gc_gc_h" >&5
+echo "${ECHO_T}$ac_cv_header_gc_gc_h" >&6
+
+fi
+if test $ac_cv_header_gc_gc_h = yes; then
+  ECL_BOEHM_GC_HEADER='gc/gc.h'
+fi
+
+
+    fi
+    if test -z "$ECL_BOEHM_GC_HEADER"; then
+       { { echo "$as_me:$LINENO: error: Boehm-Weiser garbage collector's headers not found" >&5
+echo "$as_me: error: Boehm-Weiser garbage collector's headers not found" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    ;;
+  no)
+    ECL_BOEHM_GC_HEADER='none';;
+  *)
+    { { echo "$as_me:$LINENO: error: Not a valid argument for --enable-boehm $enable_boehm" >&5
+echo "$as_me: error: Not a valid argument for --enable-boehm $enable_boehm" >&2;}
+   { (exit 1); exit 1; }; };;
+esac
 
 
 if test "${with_gmp}" = "no" ; then
